"use strict";
const keys=["diesel","electricity","n","p","k"], labels=["Diesel (L)","Strøm (kWh)","Nitrogen i mineralgjødsel (kg N)","Fosfor i mineralgjødsel (kg P)","Kalium i mineralgjødsel (kg K)"],$=id=>document.getElementById(id),fmt=n=>n===null?"Ukjent":n.toLocaleString("nb-NO",{maximumFractionDigits:3});
keys.forEach((k,i)=>{const d=document.createElement("details");d.open=true;const s=document.createElement("summary");s.textContent=labels[i];d.append(s);d.insertAdjacentHTML("beforeend",'<div class="grid"><label>Mengde <input id="'+k+'" type="number" min="0" step="any"></label><label>År for mengden <input id="'+k+'Year" type="number" value="2026"></label><label>Datagrunnlag <select id="'+k+'Evidence"><option value="user_reported">Brukeroppgitt</option><option value="measured">Målt / dokumentert</option><option value="estimated">Anslag</option></select></label><label>Kilde <input id="'+k+'Source"></label></div>');$("inputs").append(d);});
function read(){const d={schemaVersion:"0.01",year:Number($("year").value),area:$("area").value,harvest:$("harvest").value,crop:$("crop").value,productionSource:$("productionSource").value,inputYear:{},sources:{},evidence:{}};keys.forEach(k=>{d[k]=$(k).value;d.inputYear[k]=Number($(k+"Year").value);d.sources[k]=$(k+"Source").value;d.evidence[k]=$(k+"Evidence").value;});return d;}
function fill(d){if(d.schemaVersion!=="0.01")throw Error("Ukjent filversjon.");for(const k of ["year","area","harvest","crop","productionSource"])$(k).value=d[k]??"";keys.forEach(k=>{$(k).value=d[k]??"";$(k+"Year").value=d.inputYear?.[k]??d.year;$(k+"Evidence").value=d.evidence?.[k]??"user_reported";$(k+"Source").value=d.sources?.[k]??"";});$("result").replaceChildren();$("scenario").textContent="";}
function render(){try{const r=OFAKlima.calculate(read());$("status").textContent="Delregnskap • "+r.year+(r.containsEstimate?" • inneholder anslag":"");const container=$("result");container.replaceChildren();const p=document.createElement("p");p.textContent="Beregnet delsum: "+fmt(r.subtotal)+" kg CO₂e | per daa: "+fmt(r.perDaa)+" | per kg avling: "+fmt(r.perKg);container.append(p);const table=document.createElement("table");for(const row of r.rows){const tr=document.createElement("tr");for(const text of [row.label,fmt(row.value)+" × "+fmt(row.factor)+" = "+fmt(row.kgCO2e)+" kg CO₂e",row.source]){const td=document.createElement("td");td.textContent=text;tr.append(td);}table.append(tr);}container.append(table);const note=document.createElement("p");note.className="notice";note.textContent="Ukjente mengder: "+(r.missing.join(", ")||"ingen i disse fem postene")+". Uberegnede kilder: "+r.excluded.join(", ")+". Dette er ikke et totalavtrykk.";container.append(note);return r;}catch(e){$("result").replaceChildren();$("scenario").textContent="";$("status").textContent=e.message;return null;}}
$("calculate").onclick=render;
$("compare").onclick=()=>{const r=render(),pct=Number($("reduction").value);if(!r)return;const diesel=r.rows.find(x=>x.key==="diesel");if(!diesel||!Number.isFinite(pct)||pct<0||pct>100){$("scenario").textContent="Oppgi dieselmengde og reduksjon mellom 0 og 100 %.";return;}const saved=diesel.kgCO2e*pct/100;$("scenario").textContent="Med "+pct+" % mindre diesel reduseres delregnskapet med "+fmt(saved)+" kg CO₂e, til "+fmt(r.subtotal-saved)+" kg CO₂e.";};
$("save").onclick=()=>{if(!render())return;try{localStorage.setItem("ofa-klima-0.01",JSON.stringify(read()));$("storageStatus").textContent="Lagret i denne nettleseren. Last ned JSON for en sikkerhetskopi.";}catch{$("storageStatus").textContent="Nettleseren tillater ikke lokal lagring. Bruk nedlasting."; }};
$("export").onclick=()=>{const r=render();if(!r)return;const blob=new Blob([JSON.stringify({input:read(),result:r,factors:OFAKlima.factors},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="ofa-klima-"+r.year+".json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$("import").onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw Error("Filen er for stor.");const data=JSON.parse(await f.text());fill(data.input||data);render();}catch(err){$("storageStatus").textContent="Kunne ikke lese fil: "+err.message;}};
$("example").onclick=()=>{const d={schemaVersion:"0.01",year:2026,area:100,harvest:40000,crop:"Syntetisk bygg – ikke gårdsdata",productionSource:"Syntetisk eksempel",diesel:300,electricity:1000,n:1000,p:100,k:200,inputYear:{},sources:{},evidence:{}};keys.forEach(k=>{d.inputYear[k]=2026;d.sources[k]="Syntetisk eksempel";d.evidence[k]="estimated";});fill(d);render();};
$("clear").onclick=()=>{fill({schemaVersion:"0.01",year:2026});$("status").textContent="Skjema tømt. Lagret kopi er ikke slettet.";};
document.querySelectorAll("input,select").forEach(el=>el.addEventListener("input",()=>{$("result").replaceChildren();$("scenario").textContent="";$("status").textContent="Grunnlaget er endret. Beregn på nytt.";}));
try{const saved=localStorage.getItem("ofa-klima-0.01");if(saved){fill(JSON.parse(saved));$("storageStatus").textContent="Forrige grunnlag hentet fra denne nettleseren.";}}catch{}

